{
  "comments": [
    {
      "key": {
        "uuid": "94f3063a_7a381364",
        "filename": "appengine/findit/docs/flake_detector.md",
        "patchSetId": 4
      },
      "lineNbr": 73,
      "author": {
        "id": 1002882
      },
      "writtenOn": "2019-03-01T22:28:50Z",
      "side": 1,
      "message": "Per discussion offline, we should not file bugs first for CI flakes, because there are too many of them.",
      "range": {
        "startLine": 72,
        "startChar": 59,
        "endLine": 73,
        "endChar": 59
      },
      "revId": "11c8f156296051104200f0408944efbbd67928d6",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "7e600d8c_c6b7903c",
        "filename": "appengine/findit/services/flake_issue_util.py",
        "patchSetId": 4
      },
      "lineNbr": 297,
      "author": {
        "id": 1002882
      },
      "writtenOn": "2019-03-01T22:28:50Z",
      "side": 1,
      "message": "see comment above.",
      "range": {
        "startLine": 297,
        "startChar": 19,
        "endLine": 297,
        "endChar": 42
      },
      "revId": "11c8f156296051104200f0408944efbbd67928d6",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "0c3be41f_48367836",
        "filename": "appengine/findit/services/flake_issue_util.py",
        "patchSetId": 4
      },
      "lineNbr": 348,
      "author": {
        "id": 1002882
      },
      "writtenOn": "2019-03-01T22:28:50Z",
      "side": 1,
      "message": "I\u0027d suggest leaving this out for now.",
      "range": {
        "startLine": 348,
        "startChar": 14,
        "endLine": 348,
        "endChar": 38
      },
      "revId": "11c8f156296051104200f0408944efbbd67928d6",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}