{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "2d357e6c_49b46a3c",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 10,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "IIRC, quite a few users do not have the permission to launch LED jobs, which means run_remotely will not work for them.\nI would hold on adding such a statement, and fire a bug asking to fix run_locally if it does not work as expected.",
      "range": {
        "startLine": 10,
        "startChar": 2,
        "endLine": 10,
        "endChar": 27
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "779d3390_c8ed0833",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "Note that actually it is not the issue with the script, but more like the way support_3pp handles CIPD packages.",
      "range": {
        "startLine": 12,
        "startChar": 22,
        "endLine": 12,
        "endChar": 37
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4f5476cb_8b436ef2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1115868
      },
      "writtenOn": "2021-01-27T23:37:30Z",
      "side": 1,
      "message": "+Akash if you have any time to look into the source package problem with autoconf?",
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "84376efa_4ffa2529",
        "filename": "3pp/README.md",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1115868
      },
      "writtenOn": "2021-01-27T22:48:03Z",
      "side": 1,
      "message": "run_locally worked fine for me the last time I used it, which was within the last few weeks. Can you provide more detail about how you were invoking it, your OS/platform, etc?",
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "e2795d22_c91f3bee",
        "filename": "3pp/README.md",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1326772
      },
      "writtenOn": "2021-01-27T23:24:59Z",
      "side": 1,
      "message": "On linux, clean checkout, just run ./run_locally.sh\nThe full log is too long. Some errors:\nINFO:dockerbuild:Configuring Docker image for \u0027manylinux-x64\u0027...\nDEBUG:dockerbuild:Running command: [\u0027docker\u0027, \u0027inspect\u0027, \u0027gcr.io/chromium-container-registry/infra-dockerbuild/manylinux-x64:v1.4.7\u0027] (env\u003dNone; cwd\u003d/usr/local/google/home/svenzheng/infra3/.3pp_wd/3pp/wd/static_libs/ncursesw/linux-amd64/6.0/checkout)\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/__main__.py\", line 68, in \u003cmodule\u003e\n    sys.exit(main(sys.argv[1:]))\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/__main__.py\", line 63, in main\n    dockerbuild.run(args)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/dockerbuild.py\", line 391, in run\n    rc \u003d args.func(args, system)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/dockerbuild.py\", line 236, in _main_run\n    dx \u003d builder.build(plat)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/dockcross.py\", line 254, in build\n    dx, regenerated \u003d self._ensure_builder_image(plat, rebuild, upload)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/dockcross.py\", line 205, in _ensure_builder_image\n    if dx.exists():\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/dockcross.py\", line 303, in exists\n    return _docker_image_exists(self.system, self.identifier)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/dockcross.py\", line 35, in _docker_image_exists\n    rc, _, \u003d system.docker([\u0027inspect\u0027, identifier])\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/runtime.py\", line 225, in docker\n    return self.run([\u0027docker\u0027] + args, **kwargs)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/infra/tools/dockerbuild/runtime.py\", line 198, in run\n    proc \u003d subprocess.Popen(args, **kwargs)\n  File \"/usr/lib/python2.7/subprocess.py\", line 394, in __init__\n    errread, errwrite)\n  File \"/usr/lib/python2.7/subprocess.py\", line 1047, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n\nLast error:\n\nThe recipe has crashed at point \u0027Uncaught exception\u0027!\n\nTraceback (most recent call last):\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/.recipe_deps/recipe_engine/recipe_engine/internal/engine.py\", line 571, in run_steps\n    raw_result \u003d recipe_obj.run_steps(api, engine)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/.recipe_deps/recipe_engine/recipe_engine/internal/recipe_deps.py\", line 832, in run_steps\n    properties_def, api\u003dapi)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/.recipe_deps/recipe_engine/recipe_engine/internal/property_invoker.py\", line 89, in invoke_with_properties\n    arg_names, **additional_args)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/.recipe_deps/recipe_engine/recipe_engine/internal/property_invoker.py\", line 52, in _invoke_with_properties\n    return callable_obj(*props, **additional_args)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipes/3pp.py\", line 130, in RunSteps\n    to_build, platform, force_build)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/.recipe_deps/recipe_engine/recipe_engine/recipe_api.py\", line 597, in _inner\n    return func(*a, **kw)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/api.py\", line 712, in ensure_uploaded\n    ret.append(self._build_resolved_spec(spec, version, force_build))\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/.recipe_deps/recipe_engine/recipe_engine/recipe_api.py\", line 604, in _inner\n    ret \u003d func(*a, **kw)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/api.py\", line 551, in _build_resolved_spec\n    spec, version, self._infra_3pp_hash.hexdigest())\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/create.py\", line 89, in build_resolved_spec\n    spec, version, git_hash, ecosystem_hash)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/create.py\", line 102, in _build_impl\n    api, workdir, spec, version, git_hash, spec_lookup, recurse_fn)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/source.py\", line 205, in fetch_source\n    for tool in spec.unpinned_tools\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/create.py\", line 88, in \u003clambda\u003e\n    ecosystem_hash)),\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/create.py\", line 89, in build_resolved_spec\n    spec, version, git_hash, ecosystem_hash)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/create.py\", line 102, in _build_impl\n    api, workdir, spec, version, git_hash, spec_lookup, recurse_fn)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/source.py\", line 244, in fetch_source\n    source_cipd_spec, source_hash\u003dsource_hash)\n  File \"/usr/local/google/home/svenzheng/infra3/infra/recipes/recipe_modules/support_3pp/source.py\", line 482, in _source_checkout\n    \u0027but %s are extracted\u0027 % (paths,))\nAssertionError: unpack_archive\u003d\u003dtrue - expected single archive file, but [Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027COPYING.EXCEPTION\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027ChangeLog.0\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027ChangeLog.1\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027ChangeLog.2\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027ChangeLog.3\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027Makefile.am\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027Makefile.in\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027aclocal.m4\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027cfg.mk\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027configure.ac\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027maint.mk\u0027), Path([START_DIR], \u00273pp\u0027, \u0027wd\u0027, u\u0027tools\u0027, u\u0027autoconf\u0027, \u0027linux-amd64\u0027, u\u00272.69\u0027, \u0027checkout\u0027, \u0027raw_source_0.tar.gz\u0027)] are extracted\n@@@STEP_CLOSED@@@",
      "parentUuid": "84376efa_4ffa2529",
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "573bc8df_6b847ece",
        "filename": "3pp/README.md",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1115868
      },
      "writtenOn": "2021-01-27T23:37:30Z",
      "side": 1,
      "message": "The first error looks like you don\u0027t have docker installed on your system. go/docker for installation instructions if you\u0027re on the Google corp Linux image.\n\nThe second error looks like there is a malformed source package for autoconf (that is, the package contains more files than the expected source archive). I have seen this on certain packages but haven\u0027t had a chance to investigate. I believe the same error would happen on the builders, except that when you use run_locally it forces a rebuild of existing packages, while the builders skip these if the output package already exists.",
      "parentUuid": "e2795d22_c91f3bee",
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c4ac2671_de90c82e",
        "filename": "3pp/README.md",
        "patchSetId": 1
      },
      "lineNbr": 18,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "bryner@, is there any link to support this statement? I learnt this by reading the commit message in crrev.com/c/2521301 but it might be a good place.",
      "range": {
        "startLine": 18,
        "startChar": 0,
        "endLine": 18,
        "endChar": 80
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7aed87a2_1916a34c",
        "filename": "3pp/README.md",
        "patchSetId": 1
      },
      "lineNbr": 18,
      "author": {
        "id": 1115868
      },
      "writtenOn": "2021-01-27T22:48:03Z",
      "side": 1,
      "message": "I can\u0027t find anything, but we should probably document this in spec.proto.",
      "parentUuid": "c4ac2671_de90c82e",
      "range": {
        "startLine": 18,
        "startChar": 0,
        "endLine": 18,
        "endChar": 80
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "41a11855_0941bebf",
        "filename": "3pp/run_remotely.sh",
        "patchSetId": 1
      },
      "lineNbr": 46,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "nit: s/user/\u003cyour_ldap\u003e",
      "range": {
        "startLine": 46,
        "startChar": 49,
        "endLine": 46,
        "endChar": 53
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "6ab80346_7f2f36ed",
        "filename": "3pp/run_remotely.sh",
        "patchSetId": 1
      },
      "lineNbr": 61,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "nit: Add \"otherwise the recipe will download source from here rather than the updated source\"",
      "range": {
        "startLine": 61,
        "startChar": 63,
        "endLine": 61,
        "endChar": 64
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "cd745dbe_1e20a6dc",
        "filename": "3pp/run_remotely.sh",
        "patchSetId": 1
      },
      "lineNbr": 62,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "nit: s/email/your_ldap",
      "range": {
        "startLine": 62,
        "startChar": 20,
        "endLine": 62,
        "endChar": 25
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f44ab42d_8bea8afd",
        "filename": "3pp/run_remotely.sh",
        "patchSetId": 1
      },
      "lineNbr": 63,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "nit: Add \"otherwise the recipe will not upload the updated package to CIPD\"",
      "range": {
        "startLine": 63,
        "startChar": 49,
        "endLine": 63,
        "endChar": 50
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "49442f19_f7f5fcb7",
        "filename": "3pp/run_remotely.sh",
        "patchSetId": 1
      },
      "lineNbr": 66,
      "author": {
        "id": 1338159
      },
      "writtenOn": "2021-01-26T22:58:02Z",
      "side": 1,
      "message": "nit: how about just \"http://go/luci-cipd#deletepackage\"?",
      "range": {
        "startLine": 66,
        "startChar": 4,
        "endLine": 66,
        "endChar": 123
      },
      "revId": "49df2ae0289e21eb7ed7222df465ba5a31211247",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}